import { NextResponse } from 'next/server'
import React from 'react'
import { renderToBuffer, Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: 'Helvetica' },
  titulo: { fontSize: 18, fontWeight: 'bold', fontFamily: 'Helvetica-Bold', color: '#1e40af', marginBottom: 5 },
  subtitulo: { fontSize: 12, color: '#6b7280', marginBottom: 20 },
  seccion: { marginBottom: 18 },
  seccionTitulo: { fontSize: 12, fontWeight: 'bold', fontFamily: 'Helvetica-Bold', color: '#1e3a5f', marginBottom: 8, borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 4 },
  parrafo: { fontSize: 9, lineHeight: 1.5, color: '#374151', marginBottom: 6 },
  bold: { fontFamily: 'Helvetica-Bold' },
  tabla: { marginVertical: 8 },
  tablaHeader: { flexDirection: 'row', backgroundColor: '#1e40af', padding: 6, borderRadius: 2 },
  tablaHeaderTexto: { color: 'white', fontSize: 8, fontWeight: 'bold', fontFamily: 'Helvetica-Bold' },
  tablaFila: { flexDirection: 'row', padding: 6, borderBottomWidth: 0.5, borderBottomColor: '#e5e7eb' },
  tablaFilaPar: { backgroundColor: '#f9fafb' },
  tablaTexto: { fontSize: 8, color: '#374151' },
  alerta: { backgroundColor: '#fef3c7', borderWidth: 1, borderColor: '#f59e0b', borderRadius: 4, padding: 8, marginVertical: 8 },
  alertaTexto: { fontSize: 8, color: '#92400e' },
  verde: { backgroundColor: '#ecfdf5', borderWidth: 1, borderColor: '#10b981', borderRadius: 4, padding: 8, marginVertical: 8 },
  verdeTexto: { fontSize: 8, color: '#065f46' },
  pie: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 7, color: '#9ca3af' },
})

export async function GET() {
  const doc = React.createElement(Document, {},
    // PAGINA 1: Resumen de impuestos
    React.createElement(Page, { size: 'A4', style: s.page },
      React.createElement(Text, { style: s.titulo }, 'GUIA DE IMPUESTOS - ABASTECER EMPRESARIAL S.A.S.'),
      React.createElement(Text, { style: s.subtitulo }, 'NIT 902088758-4 | Regimen Simple de Tributacion (RST) + IVA'),

      // Seccion 1
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '1. IMPUESTOS QUE PAGA ABASTECER'),
        React.createElement(Text, { style: s.parrafo }, 'Al estar en Regimen Simple, solo se pagan DOS cosas:'),
        React.createElement(View, { style: s.tabla },
          React.createElement(View, { style: s.tablaHeader },
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 80 } }, 'Impuesto'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 120 } }, 'Que es'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 80 } }, 'Tasa'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 80 } }, 'Frecuencia'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, flex: 1 } }, 'Como se paga'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80, fontFamily: 'Helvetica-Bold' } }, 'IVA'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'IVA cobrado menos IVA pagado'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, '19% (la diferencia)'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, 'Bimestral'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'Formulario 2593 en MUISCA'),
          ),
          React.createElement(View, { style: { ...s.tablaFila, ...s.tablaFilaPar } },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80, fontFamily: 'Helvetica-Bold' } }, 'Regimen Simple'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'Unifica: Renta + ICA + Ind. y Comercio'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, '1.8% - 5.4% de ingresos'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, 'Anticipo bimestral + anual'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'Recibo electronico SIMPLE'),
          ),
        ),
        React.createElement(View, { style: s.verde },
          React.createElement(Text, { style: s.verdeTexto }, 'NO hay mas impuestos. El Regimen Simple unifica todo. Las retenciones que te hacen los clientes se DESCUENTAN de lo que debes pagar, pero CADA UNA DESCUENTA SU PROPIO IMPUESTO: la reteIVA descuenta el IVA, y la retefuente y la reteICA descuentan el Simple. No se pueden cruzar entre si.'),
        ),
      ),

      // Seccion 2
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '2. CUANTO SEPARAR DE CADA VENTA'),
        React.createElement(Text, { style: s.parrafo }, 'Regla: De cada venta, separar para impuestos:'),
        React.createElement(View, { style: s.tabla },
          React.createElement(View, { style: s.tablaHeader },
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 150 } }, 'Concepto'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 100 } }, 'Cuanto'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, flex: 1 } }, 'Ejemplo (venta subtotal $1.280.000)'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 150 } }, 'IVA neto (cobrado - pagado)'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'IVA venta - IVA compra'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, '$243.200 - $152.000 = $91.200'),
          ),
          React.createElement(View, { style: { ...s.tablaFila, ...s.tablaFilaPar } },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 150 } }, 'Regimen Simple (provision)'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, '5% del subtotal'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, '$1.280.000 x 5% = $64.000'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 150 } }, '(-) Retenciones que te hicieron'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'Restar lo retenido'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, '-$36.480 (ya te lo descontaron)'),
          ),
          React.createElement(View, { style: { ...s.tablaFila, ...s.tablaFilaPar } },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 150, fontFamily: 'Helvetica-Bold' } }, 'TOTAL A SEPARAR'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100, fontFamily: 'Helvetica-Bold' } }, 'Suma de arriba'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1, fontFamily: 'Helvetica-Bold' } }, '$91.200 + $64.000 - $36.480 = $118.720'),
          ),
        ),
        React.createElement(View, { style: s.alerta },
          React.createElement(Text, { style: s.alertaTexto }, 'REGLA RAPIDA: Si no quieres complicarte, separa el 10% del total de cada venta. Asi nunca te faltara.'),
        ),
      ),

      // Seccion 3
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '3. RETENCIONES - LOS DOS CASOS'),
        React.createElement(Text, { style: { ...s.parrafo, fontFamily: 'Helvetica-Bold' } }, 'CASO A: El cliente SI retiene (ej: Evolti, empresas grandes)'),
        React.createElement(Text, { style: s.parrafo }, '- Te pagan MENOS de lo facturado. La diferencia son retenciones.'),
        React.createElement(Text, { style: s.parrafo }, '- Retefuente: ~2.5% del subtotal. ReteICA: ~3.5 por mil del subtotal. ReteIVA: 15% del IVA (no siempre).'),
        React.createElement(Text, { style: s.parrafo }, '- A fin de año les pides el CERTIFICADO DE RETENCION y lo cruzas con tu declaracion.'),
        React.createElement(Text, { style: s.parrafo }, '- Lo que te retuvieron se DESCUENTA de tu impuesto. NO es perdida.'),
        React.createElement(Text, { style: { ...s.parrafo, fontFamily: 'Helvetica-Bold', marginTop: 8 } }, 'CASO B: El cliente NO retiene (clientes pequenos, personas naturales)'),
        React.createElement(Text, { style: s.parrafo }, '- Te pagan el 100% de la factura.'),
        React.createElement(Text, { style: s.parrafo }, '- TU debes separar el 5% del subtotal para pagar impuesto al final.'),
        React.createElement(Text, { style: s.parrafo }, '- Ese 5% lo guardas y lo usas para pagar el anticipo bimestral del Simple.'),
      ),

      React.createElement(Text, { style: s.pie }, 'ABASTECER EMPRESARIAL S.A.S. | NIT 902088758-4 | Guia interna de impuestos | Pagina 1 de 2'),
    ),

    // PAGINA 2: Calendario y procedimientos
    React.createElement(Page, { size: 'A4', style: s.page },
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '4. CALENDARIO DE PAGOS 2026-2027'),
        React.createElement(View, { style: s.tabla },
          React.createElement(View, { style: s.tablaHeader },
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 80 } }, 'Bimestre'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 100 } }, 'Periodo'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, width: 120 } }, 'Fecha limite pago'),
            React.createElement(Text, { style: { ...s.tablaHeaderTexto, flex: 1 } }, 'Que se paga'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80, fontFamily: 'Helvetica-Bold' } }, '4to (primero)'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'Jul - Ago 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'Septiembre 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'IVA bimestral + Anticipo Simple'),
          ),
          React.createElement(View, { style: { ...s.tablaFila, ...s.tablaFilaPar } },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, '5to'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'Sep - Oct 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'Noviembre 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'IVA bimestral + Anticipo Simple'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, '6to'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'Nov - Dic 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'Enero 2027'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'IVA bimestral + Anticipo Simple'),
          ),
          React.createElement(View, { style: { ...s.tablaFila, ...s.tablaFilaPar } },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80, fontFamily: 'Helvetica-Bold' } }, 'ANUAL'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, 'Todo 2026'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120, fontFamily: 'Helvetica-Bold' } }, 'Abril 2027'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'Declaracion Simple (cruce retenciones)'),
          ),
          React.createElement(View, { style: s.tablaFila },
            React.createElement(Text, { style: { ...s.tablaTexto, width: 80 } }, 'Certificados'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 100 } }, '-'),
            React.createElement(Text, { style: { ...s.tablaTexto, width: 120 } }, 'Ene-Mar 2027'),
            React.createElement(Text, { style: { ...s.tablaTexto, flex: 1 } }, 'Pedir certificados de retencion a clientes'),
          ),
        ),
      ),

      // Seccion 5
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '5. COMO PAGAR EL IVA + SIMPLE (paso a paso)'),
        React.createElement(Text, { style: s.parrafo }, '1. Entrar al MUISCA (muisca.dian.gov.co) como la empresa'),
        React.createElement(Text, { style: s.parrafo }, '2. Menu → "Diligenciar y presentar" → Recibo Electronico SIMPLE (formulario 2593)'),
        React.createElement(Text, { style: s.parrafo }, '3. Llenar: Ingresos del bimestre, IVA cobrado, IVA pagado (descontable), Anticipo Simple'),
        React.createElement(Text, { style: s.parrafo }, '4. El sistema calcula cuanto debes'),
        React.createElement(Text, { style: s.parrafo }, '5. Generar recibo de pago → Pagar por PSE (desde Bold o banco)'),
      ),

      // Seccion 6
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '6. COMO FUNCIONAN LOS ANTICIPOS DEL SIMPLE'),
        React.createElement(Text, { style: s.parrafo }, 'En vez de pagar todo al final del año, pagas de a poquitos cada 2 meses:'),
        React.createElement(Text, { style: s.parrafo }, '- Cada bimestre: pagas ~3.5% de los ingresos de ese bimestre (anticipo)'),
        React.createElement(Text, { style: s.parrafo }, '- Al final del año (abril 2027): sumas todo lo que vendiste, calculas el impuesto real'),
        React.createElement(Text, { style: s.parrafo }, '- Restas: anticipos que ya pagaste + SOLO la retefuente y la reteICA que te hicieron'),
        React.createElement(Text, { style: s.parrafo }, '- La reteIVA NO va aqui: esa se resta en la declaracion bimestral de IVA'),
        React.createElement(Text, { style: s.parrafo }, '- Si falta: pagas la diferencia. Si sobra: saldo a favor para el proximo año.'),
        React.createElement(View, { style: s.verde },
          React.createElement(Text, { style: s.verdeTexto }, 'EJEMPLO: Vendiste $50M en el año. Impuesto: $1.750.000. Ya pagaste anticipos $1.050.000 + retefuente/reteICA $400.000 = $1.450.000. Solo falta pagar $300.000 en abril.'),
        ),
        React.createElement(View, { style: s.alerta },
          React.createElement(Text, { style: { ...s.alertaTexto, fontFamily: 'Helvetica-Bold', fontSize: 10 } }, 'CADA RETENCION DESCUENTA SU PROPIO IMPUESTO'),
          React.createElement(Text, { style: { ...s.alertaTexto, marginTop: 4 } }, '• ReteIVA (normalmente 15% del IVA) -> descuenta el IVA, en la declaracion bimestral de IVA'),
          React.createElement(Text, { style: s.alertaTexto }, '• Retefuente -> descuenta el Simple'),
          React.createElement(Text, { style: s.alertaTexto }, '• ReteICA -> descuenta el Simple (el ICA va dentro del Simple)'),
          React.createElement(Text, { style: { ...s.alertaTexto, marginTop: 4 } }, 'La plata que apartas es la MISMA. Lo que cambia es en cual declaracion la usas. Si la usas en la equivocada, esa declaracion queda corta y la DIAN te cobra la diferencia con intereses, asi la otra quede pagada de mas.'),
          React.createElement(Text, { style: { ...s.alertaTexto, marginTop: 4 } }, 'OJO: en el Regimen Simple, por regla general los clientes NO deben practicarte retefuente (Art. 911 del Estatuto Tributario). Si en una factura te descuentan retefuente, verificalo antes de darlo por hecho. La reteIVA en pagos electronicos si aplica.'),
        ),
      ),

      // Seccion 7
      React.createElement(View, { style: s.seccion },
        React.createElement(Text, { style: s.seccionTitulo }, '7. REGLA DE ORO'),
        React.createElement(View, { style: s.alerta },
          React.createElement(Text, { style: { ...s.alertaTexto, fontFamily: 'Helvetica-Bold', fontSize: 10 } }, 'DE CADA VENTA SEPARAR:'),
          React.createElement(Text, { style: { ...s.alertaTexto, marginTop: 4 } }, '• IVA neto (IVA cobrado - IVA pagado en compras) → Para pago bimestral IVA'),
          React.createElement(Text, { style: s.alertaTexto }, '• 5% del subtotal (sin IVA) → Para anticipo Regimen Simple'),
          React.createElement(Text, { style: s.alertaTexto }, '• Restar lo que el cliente te retuvo (eso ya esta "pagado"), pero en su propio bolsillo: la reteIVA del bolsillo IVA, y la retefuente/reteICA del bolsillo Simple'),
          React.createElement(Text, { style: { ...s.alertaTexto, marginTop: 4, fontFamily: 'Helvetica-Bold' } }, 'REGLA RAPIDA: Separar el 10% del total de cada venta. Asi NUNCA te faltara.'),
        ),
      ),

      React.createElement(Text, { style: s.pie }, 'ABASTECER EMPRESARIAL S.A.S. | NIT 902088758-4 | Guia interna de impuestos | Pagina 2 de 2'),
    ),
  )

  const buffer = await renderToBuffer(doc)

  return new NextResponse(Buffer.from(buffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="Guia_Impuestos_Abastecer_2026.pdf"',
    },
  })
}
